
default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: thirdror_development


test:
  <<: *default
  database: thirdror_test


production:
  <<: *default
  database: thirdror_production
  password: <%= ENV['THIRDROR_DATABASE_PASSWORD'] %>
